### ISSUE TITLE
Android Basics issue: Expecting '}'

### ISSUE THREAD

**Issue by joshuajprenuer** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#242]
How do I get rid of the error: Expecting '}'  in create a cake with layers and candles lesson? I cant get past this error.
![Screenshot (38)](https://user-images.githubusercontent.com/97404020/163662671-772449f7-2198-4e35-9bc5-5a527a8700d9.png)

**Comment by xpyramiid** [comment]
put a space after the "repeat(age + 2)" before the "{"

**Comment by osuleymanova** [comment]
@xpyramiid 
Thank you for reaching out to us. In your case in fun main () { the error can be fixed by adding the closing "}":

https://pl.kotl.in/nKyPZpoo9

The code snippet provided in the codelab is the part of main function so there is no extra "}":

![Screen Shot 2022-07-29 at 5 19 47 PM](https://user-images.githubusercontent.com/86437155/181863003-6e3a49c3-e047-4333-ae74-4ba8d3087800.png)
