### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by HyungJune** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#40]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#1

**In which task and step of the codelab can this issue be found?**
 Create your first app -> Create an Empty Activity project

**Describe the problem**
The Welcome to Android Studio window is different from the version 4.1.3.

In Android Basics:
![image](https://user-images.githubusercontent.com/5601663/114045605-17c89c80-98c3-11eb-9aba-2428389fa5f6.png)

In my Android Studio (version 4.1.3, windows):
![image](https://user-images.githubusercontent.com/5601663/114045730-375fc500-98c3-11eb-92b0-edf5c5b09e82.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @HyungJune,

Thank you for reaching out to us. Since the date of your report the Welcome to Android Studio window screenshot was updated to the AS version Bumblebee:
![Screenshot 2023-04-03 at 12 59 00 PM](https://user-images.githubusercontent.com/86437155/229614888-0c0152d0-12d2-4555-9955-e387190c2556.png)

In the nearest future it will be updated again.
