### ISSUE TITLE
Android Basics: first-template-project

### ISSUE THREAD

**Issue by Harshil-Jani** [google-developer-training/android-basics-kotlin-birthday-card-app-solution#70]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-first-template-project?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-two%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-first-template-project#1

**In which task and step of the codelab can this issue be found?**
Task 2 , Step 12
**Describe the problem**
In the picture in Step 12, Task 2 , Android Platform / API Version Distribution. The documentation consist the data upto Oreo i.e Android 8.1 and the Cumulative distribution is also upto that. With new versions being launched after 8.1 The cumulative distribution shall also be changed. Fix the image with new latest Data.

![Android Docs Issue Report](https://user-images.githubusercontent.com/79367883/124395172-41595e80-dd20-11eb-9447-ca6c10b344e1.png)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment]
Thank you @Harshil-Jani for reporting this issue. We're working to improve Android ecosystem insights. For now, more information can be found on the [Distribution Dashboard](https://developer.android.com/about/dashboards) page. As this is being actively worked on, and this issue is not directly related to the first-template-project, I'll close out this issue.
